language: node_js
node_js:
- "0.10.36"
install:
- npm install
before_script:
  - chmod +x deploy.sh
script:
  - npm test
sudo: false
deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: dev
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: release
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master

env:
  matrix:
    - CXX=g++-4.8
  global:
    # DEV_MEMBER_ES_HOST
    - secure: kNVo5r0jRIKCwZp1lWD1AKDJ3eEIf2bGIqg1o7USxpyV4XLY8GInxYs+gemX3ovm3lxDhwi3kQLY7VC98XL6+zNaYaJNiW4pEcrFcVtmVJ8//D4tEEATmsr4pR4z3oOesGU/AdS37i5VYqG/esIZvRSNwu7AQ2WMICg8Qu+MG83XYCx0V/RYwF0zCg/N1Ns+FlP0IvgZdwGrM7o35InJ3pgNFBpJgqC7bERJS6DyTq565fKriI10VDx1CtT/OYEE6DAtUCF49gPtbOCoN8iWTo828N+oMoZBqfopQfWw2URV69+qbNCKqv5GnuYaeZFIYmwpSoBpPVh4kcFkH1kp7ZoA7jIKRdMkEvvvr6JKu/11G06jhQ59oQTMQnsZT3ToDClWKyIHtsseJlzcmC7TQvAHV2MhY4I6O322rqRhafDoothOEu0f0tj+Um5DCK366BFF3RUf4t2deD0oIUMHEkOEClOwSdW1BZrJSJsml49sY6SQS3RamDbRXKffbrgywaE4646agVHGwsAJNf6jfzzeyu2C5BfwI+HaS8SVE/pPnb5bpML6ODc0dZ75ZpHNirFhlDHnlRK6yf+BuUSSWZTrNUDt+UF5HJTLVsLbZtDlmSH30YOc9DvrvZ8oWud6c+Sj3rXvjTmAJaUZi6/XWEU0GGwzPssY52byXL+TiKE=

    # DEV_AWS_KEY
    - secure: aGNnOjVW8W5/cFGhMMZqW6TSNcPrHjRD5WDPAwq4bi4MgvxXv3wyMxedjnWImT+HRx8rj6IiP0ZqGxtoXS9T4EgOzV6WfmzF70HMXQi/+3qLDFRP4gJHmnrYQ0AKwel64OmTumbGPF6mexFgKnCfqvfYKMZ60pMbSBPUCsTCJ3v7xFn03NyF70b+APOUNtopNAp+1BVGdq5r0hCBzaNqPwCCQ3IOxYxyDwp6vZyPdJuEXMaOhEE9bqOADa618O481WtzQ9/Uc0PEJ3PFOxPdIVNmF9+FxvnTwFAivO0DIkYUjl6T7tt8EVyWcwwTmFpyYAURNHjQMjFJatBs5pC/knBhjVwjnE0WUZySrnYftXqAMUd+B1T9qml5QmtA4ATyO9N32tdBriwNoK/Ch2FkCUE6azeeTOMjbpq5sIfhF4iCft6jpfp/sLtAfG05X4nhx4UF2I4TE/u+ZR2bTJVYWtOYB8nVnRwM3zJvnGd9fS7uNyxxkd71a3V0JrzniPBrjgbhd2OPhS4U3zT6IRrlEn//Quy6u/KE86ygqjZIq+2xjrzaOMfcP5J8gHXsM5CStGIZTkk0sdqVzH+YFPj8MejgAfailWWPRkDLBwt1AD2cGaXj7k8Y4DMWaednVpkfsFyQ9KC9+KKGCrWI2SlmOn0JDB7DWqEkfr8RpR/izy8=
    # DEV_AWS_SECRET
    - secure: mjYzQJQF04TScyN8wBg3NisVJwuefOAwFj5TQAFEMj+5SYh7dERx8CMS51m6QWPq9D1hMi5gYl1hJcHdrhj5E0jZRx6HF2eWlSCQGiWl18youHEx4xmZe/lfYHq6pP57ys2CHaMNBrTlwQOVnJjY68VGtfD2dwVbkMYofM00MmU8ZQafJZNVi6yxAepFJevunYcaLxFJH2/C4bDcQv7WXQfHHFXLMzomTBYtHiduvKy1gVueyb8fG2ul0H6+UdL1juDtfs8dKvTflnYpf04pCNA0Aj6xcsGKaLeU6/a5J5EWcT4VV66rf1df0WexxrSMIUIcll2H8x22t+z3jEBJ+BBvJ7W1ojYLN7MnTy4tvDWqDokeyRjyBg1af8wyn9WmL/JrTMxsomuN6YeqUmUn8D0115gpJl831P5kQLWGZnPVhd1C7gEOkGWn6+P0Verx8j3F60Mr5xgqwPdBL1L+IjLog0w+f7KB8KQ3tJ94+hEpxNveV0Wn5M256meajyeY1k9YmCWI2DbSojRae8gwiU7/mDGwMHjoPaYRttXD7t3095dFClUafzQA6izyk6Uhz+SbCbpqs94RzMl2ny3y0siNDKTw28p5Vg35CUU+kib3JkzxQQ9HkKeqX0ufBJhGl9EAsR9KAiOuoGXH93tG46UIwaXIrj4gQtixl8P0jNM=
    # DEV_AWS_LAMBDA_ROLE_ARN
    - secure: R8KfL51csAq/vwJBFAZT5FMql7z00HHUwfY6m5dEOTcVQDOiAFawVF1q3x5HpotXQLF21tgUvgU7kvvDtN86DyZMxg62w0x8VVar3zmxQJUalUWXeHE9wbrb45Gk6F8D7AWIGzJFgP0TQjpv/jiOJ9kH+PDXhwYe43ngz8J+7wK0uZT8byn74BYqqrz5gybSFA+iM1+TKmDOyJk2sBOcX5xWsTGgjM1BbVpom9c1HxxmAvt/OaMOhgsPJO2Wv61BwrnIW6IygfHbDDzl0M3ohW191Pt4UmhkVDb3pO6NqaLRgYRWCeZXroQCJzfjIj0ITBSbcoYUGnqPLSccDaIPXsSA4ytBQe1K6D9urb8ZvMXVoWJOaAWFqEIH2/4p0w8hfF8l+G4Lodk//rh2x6FNjFDXpMEpmBp1q85Uk55u/D84lm+Wgn6EXA+pg3BTxEPdSMhUK9URNj3cJ10oNwkCA9mZII2Xis4CprwLjJ7eouVs3gy5AHCInD/wdGQg2J4JoBFp5vKlfLk7joBxLaKmDHI/qXav7dxpINStvJKbvUkCc+PYnxrAZG3xy5rnLWiTwb9I8cF6Dfrw+huCXRxONzDsep7MBNG8r5MJilE/g8cAzjkNDZStZP4VP5VD1Jv5saVVVAQCuLRWbJnVW4e7Ywxy9uCRociFzhPjFSFwONQ=


